export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_FAILL = 'FETCH_PRODUCTS_FAILL';
// export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const SET_CAROUSEL_PRODUCTS = 'SET_CAROUSEL_PRODUCTS';
// export const SET_SHOP_PRODUCTS = 'SET_SHOP_PRODUCTS';
export const SET_SHOP_DATA = 'SET_SHOP_DATA';
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const SAVE_SHOP_STATE = 'SAVE_SHOP_STATE';